f = open(r'c:\Users\Admin\Downloads\gpcgroup\gpcgroup.html', encoding='utf-8')
c = f.read()
f.close()

print("File size: {} KB".format(round(len(c)/1024, 1)))
print("Brand blue #005a9b: {}".format('#005a9b' in c))
print("Brand amber #fbb60c: {}".format('#fbb60c' in c))
print("about.png: {}".format('images/about.png' in c))
print("il1.jpeg: {}".format('images/il1.jpeg' in c))
print("il2.jpeg: {}".format('images/il2.jpeg' in c))
print("cc.jpeg: {}".format('images/cc.jpeg' in c))
print("Scroll reveal: {}".format('reveal-left' in c))
print("Ticker animation: {}".format('ticker-scroll' in c))
print("Counter animation: {}".format('data-target' in c))
print("Mobile menu: {}".format('nav__mobile' in c))
print("About section: {}".format('id="about"' in c))
print("Services section: {}".format('id="services"' in c))
print("Fleet section: {}".format('id="fleet"' in c))
print("Contact section: {}".format('id="contact"' in c))
print("Sora font: {}".format('Sora' in c))
print("Plus Jakarta Sans: {}".format('Plus Jakarta Sans' in c))
print("ALL OK!")
